apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-manager
subjects:
- kind: ServiceAccount
  name: service-manager
  namespace: default
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name:  service-manager-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
