apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-manager-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log", "pods/exec", "pods/ephemeralcontainers", "services", "namespaces"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
